services:
  offer-service:
    build:
      context: .
    ports:
      - '4060:4060'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: offerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - '5436:5432'
    volumes:
      - offer_service_postgres:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

volumes:
  offer_service_postgres:
