services:
  # Express Server
  auth-service:
    build: 
      context: .
      dockerfile: Dockerfile
    image: auth-service:latest
    container_name: auth-service
    ports:
    - '${PORT}:${PORT}' 
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      PORT: 4040
    depends_on:
      - postgres
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ./.env
    restart: always
volumes:
  db-data:
